export const proyectosAutonomo = {
    id: 'autonomo',
    img: require('../../images/proyectos-autonomo.png').default,
    alt: 'Estacion Autonoma',
    topLine: 'HARDWARE Y SOFTWARE',
    title: 'Estación autónoma de monitoreo acústico pasivo',
    description: 'Monitoreo remoto de señales acústicas en el mar compuesto por un hidrófono diseñado por el grupo con su correspondiente preamplificador. El hidrófono capta las ondas sonoras propagandose en el mar para luego enviar la señal a un sistema de detección embebido en la boya oceanográfica. El sistema digitaliza y almacena los datos acústicos, para luego transmitirlos a una estación receptora ubicada en la costa con una antena WiFi',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    imgStart: false,
    dark: false,
    primary: false,
    darkText: true,
    linkTo: '#', 
};

export const proyectosHidrofonoTurismo = {
    id: 'autonomo',
    img: require('../../images/proyectos-turismo.JPG').default,
    alt: 'Hidrófono Turismo',
    topLine: 'HARDWARE',
    title: 'Hidrófono para ecoturismo',
    description: 'Sistema de escucha compuesto por un hidrófono diseñado específicamente y un sistema de distribución a auriculares Bluetooth',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    imgStart: true,
    dark: true,
    primary: true,
    darkText: false,
    linkTo: '#', 
};

export const proyectosHidrofonoCiencia = {
    id: 'autonomo',
    img: require('../../images/proyectos-hidrofono-ciencia-3.jpg').default,
    alt: 'Hidrofono Investigación',
    topLine: 'HARDWARE Y SOFTWARE',
    title: 'Hidrófono para investigación',
    description: 'Sistema de grabación incluyendo hidrófono con rango de frecuencias utilizables hasta 250 kHz, conversor A/D y software de grabación y monitoreo desarrollado en Python',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    imgStart: false,
    dark: false,
    primary: false,
    darkText: true,
    linkTo: '#', 
};

export const proyectosHidrofonoTesis = {
    id: 'autonomo',
    img: require('../../images/proyectos-hidrofono-tesis.png').default,
    alt: 'Hidrofono Tesis',
    topLine: 'HARDWARE',
    title: 'Hidrófono prototipo investigación',
    description: 'Tesis de ingeniería de Nicolás Valese. Hidrófono con rango de frecuencias hasta 200 kHz con su correspondiente preamplificador',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    imgStart: true,
    dark: true,
    primary: true,
    darkText: false,
    linkTo: '#', 
};

export const proyectosAmplificador = {
    id: 'autonomo',
    img: require('../../images/proyectos-amplificador.jpg').default,
    alt: 'Estacion Autonoma',
    topLine: 'HARDWARE',
    title: 'Amplificador de carga',
    description: 'Amplificador de carga para registro de señales provenientes de sensores piezoléctricos',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    imgStart: false,
    dark: false,
    primary: false,
    darkText: true,
    linkTo: '#', 
};


export const proyectosDetector = {
    id: 'autonomo',
    img: require('../../images/proyectos-detector.png').default,
    alt: 'Estacion Autonoma',
    topLine: 'SOFTWARE',
    title: 'Detector y clasificador de clicks NBHF',
    description: 'Detector y clasificador de click NBHF emitidos por cetáceos desarrollado en Matlab',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    imgStart: true,
    dark: true,
    primary: true,
    darkText: false,
    linkTo: '#', 
};